version: "3.7"

services:

  postgresql:
    image: postgres:12.2-alpine
    volumes:
      - .data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  api:
    image: api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn -b 0.0.0.0:5000 --workers=4 gloria:app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - postgresql
    restart: always